import os
BOATRACE_STORAGE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/'
BOATRACE_BACE_INFO_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/boatrace_bace_info.csv'
BOATRACE_BACE_INFO_CSV_BK = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/boatrace_bace_info_bk.csv'
BOATRACE_DEADLINE_TIMES_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/boatrace_deadline_times.csv'

ODDS_ASHIYA_2RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_ashiya_2rentan.csv'
ODDS_ASHIYA_3RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_ashiya_3rentan.csv'
ODDS_OMURA_2RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_omura_2rentan.csv'
ODDS_OMURA_3RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_omura_3rentan.csv'
ODDS_TOKUYAMA_2RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_tokuyama_2rentan.csv'
ODDS_TOKUYAMA_3RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_tokuyama_3rentan.csv'
ODDS_RACE_ORDER_2RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_race_order_2rentan.csv'
ODDS_RACE_ORDER_3RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_race_order_3rentan.csv'
MARGE_ODDS_ASHIYA_2RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_marge_ashiya_2rentan.csv'
MARGE_ODDS_ASHIYA_3RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_marge_ashiya_3rentan.csv'
MARGE_ODDS_OMURA_2RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_marge_omura_2rentan.csv'
MARGE_ODDS_OMURA_3RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_marge_omura_3rentan.csv'
MARGE_ODDS_TOKUYAMA_2RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_marge_tokuyama_2rentan.csv'
MARGE_ODDS_TOKUYAMA_3RENTAN_CSV = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) +'/storage/odds_marge_tokuyama_3rentan.csv'

BET_3TAN  = '3tan'
BET_2TAN  = '2tan'
BET_3PUKU = '3puku'
BET_2PUKU = '2puku'
BET_2ALL  = '2all'
BET_ALL   = '9'