"""
Django settings for quantumgrail project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .base import *

INSTALLED_APPS += (
                   # 'debug_toolbar', # and other apps for local development
                   )
DEBUG = False
STATIC_URL = '/datavault/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []

MEDIA_URL = '/datavault/temp_media/'
ENV = 'production'
